name: Production deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Production version deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          VUE_APP_API_KEY: ${{ secrets.API_KEY }}
          VUE_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          VUE_APP_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VUE_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VUE_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        run: |
          npm install -g firebase-tools
          npm install
          npm run build:firebase
          firebase deploy --only hosting:develop --token $FIREBASE_TOKEN --project develop
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure()
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()
